<?php if (!$this->update) { ?>
<h1>Role Permissions</h1>
<script language="javascript">

function acl_update(role, action, can){
    $.post( '<?php echo $this->baseUrl('/member/acl') ?>', 
    {acl: {role: role, action: action, can: can}, update: 1}
    , function(table){$('#acl_table').html(table)} )
}
</script>
<?php } ?>
<div id="acl_table">
<table class="list acl">
    <tr>
        <th><i>Actions</i></th>
        <?php foreach(($roles = array_keys($this->grants)) as $role){ ?>
        <th><?php echo $role ?></th>
        <?php } ?>
    </tr>

    <?php foreach($this->actions as $action) {  ?>
    <tr>
    <th><?php echo $action ?></th>

    <?php foreach($roles as $role){ ?>
    <?php $can = $this->grants[$role][$action];
    switch ($can){

        case NULL:
            echo '<td class="null" ';
            echo ' onClick="acl_update(\'', $role , '\', \'',$action ,'\',\'yes\')';
            echo '">???</td>';
            break;

        case 1:
            echo '<td class="yes" ';
            echo ' onClick="acl_update(\'', $role , '\', \'',$action ,'\',\'no\')';
            echo '">YES</td>';
            break;

        case 0:
            echo '<td class="no" ';
            echo ' onClick="acl_update(\'', $role , '\', \'',$action ,'\',\'delete\')';
            echo '">NO</td>';
            break;
    }
    ?>
    <?php } ?>

    </tr>
    <?php } ?>

</table>
</div>
<?php if (!$this->update) { ?>

<hr />

<?php echo $this->partial('forms/add_grant.phtml') ?>
<?php } ?>