<h1>Members</h1>

<?php if (FALSE !== $this->members) { ?>
<table class="list">
    <tr>
        <th>Alias</th>
        <th>Name</th>
        <th>Email</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->members as $member) { ?>
    <tr>
        <td><?php echo $member['alias'] ?></td>
        <td><?php echo $member['name'] ?></td>
        <td><?php echo $member['email'] ?></td>
        <td class="button" 
            onClick="document.location='<?php echo $this->baseUrl('/member/edit/id/' . $member->id) ?>'">
        Edit</td>
    </tr>
    <?php } ?>
</table>
<?php } ?>

<?php if ($this->user) {
         echo $this->partial('tickets/member.phtml', array('member' => $this->user));
} else { ?>
    <div id="tabs">
        <ul>
            <li><a href="<?php echo $this->baseURL('/member/signin/ticket/1') ?>">Sign In</a></li>
            <li><a href="<?php echo $this->baseURL('/member/join/ticket/1') ?>">Join Us</a></li>
        </ul>
    </div>
<script language="javascript">
    $(function() {
        $( "#tabs" ).tabs();
    });
</script>
<?php
    } 