<?php

$role_model = new Gettogether_Model_Roles();
$roles = $role_model->role_names(FALSE, $this->scope, $this->scope_id);

?>

<form method="post" action="/member/addrole" style="width: 40em">
<h2>Add Role to member &quot;<?php echo $this->member->name ?>&quot; (<?php echo $this->member->alias ?>)</h2>
<p>Scope: <?php echo $this->scope ?>:<?php echo $this->scope_id ?></p>
<input type="hidden" name="addrole[member]" value="<?php echo $this->member->id ?>" />
<input type="hidden" name="addrole[scope]" value="<?php echo $this->scope ?>" />
<input type="hidden" name="addrole[scope_id]" value="<?php echo $this->scope_id ?>" />
<table>
    <tr>
        <th><label>Role</label></th>
        <td><select name="addrole[role]">
                <option value="">Select Role</option>
                <?php foreach($roles as $role){ ?>
                <option value="<?php echo $role ?>"><?php echo $role ?></option>
                <?php } ?>
            </select>
        </td>
    </tr>

    <tr>
        <td colspan="2" style="text-align: center"><input type="submit"
        class="button submit"  value="Add Role to Member" /></td>
    </tr>
</table>
</form>
