

<form method="post" action="/acl/add" style="width: 40em">
<h2>Add Role</h2>
<table>
    <tr>
        <th><label>Role</label></th>
        <td><input type="text" name="role[role]" value="" />
        </td>
    </tr>

    <tr>
        <th><label>Label</label></th>
        <td><input type="text" name="role[name]" value="" />
        </td>
    </tr>

    <tr>
        <td colspan="2" style="text-align: center"><input type="submit"
        class="button submit"  value="Add Role" /></td>
    </tr>
</table>
</form>
