<table class="ticket">
    <tr>
        <th>Event</th>
        <td><?php echo $this->event->name ?></td>
    </tr>
    <tr>
        <th>Description</th>
        <td><?php echo $this->event->description ?></td>
    </tr>
    <tr>
        <th>Start</th>
        <td><?php echo $this->event->start_date ?></td>
    </tr>
    <tr>
        <th>City</th>
        <td><?php echo $this->event->city ?></td>
    </tr>
    <tr>
        <th>State</th>
        <td><?php echo $this->event->state ?></td>
    </tr>
    <tr>
        <th>Zip</th>
        <td><?php echo $this->event->zip ?></td>
    </tr>
</table>