<?php if (!$this->ticket) { ?>
<div id="acl_table">
<?php } ?>
<table class="list acl">
    <thead>
    <tr>
        <th><i>Tasks</i></th>
        <?php foreach($this->roles as $role){ ?>
        <th><?php echo $role ? $role : 'default' ?></th>
        <?php } ?>
    </tr>
    </thead>
    
    <?php foreach($this->tasks as $task) {  ?>
    <tr>
    <th><?php echo $task ?></th>

    <?php foreach($this->roles as $role) if (array_key_exists($role, $this->grants)){ ?>
    <?php $can = array_key_exists($task, $this->grants[$role]) ? $this->grants[$role][$task] : NULL;
    switch ($can){

        case NULL:
            echo '<td class="null" ';
            echo ' onClick="acl_update(\'', $role , '\', \'',$task ,'\',\'yes\')';
            echo '">???</td>', "\n";
            break;

        case 1:
            echo '<td class="yes" ';
            echo ' onClick="acl_update(\'', $role , '\', \'',$task ,'\',\'no\')';
            echo '">YES</td>', "\n";
            break;

        case 0:
            echo '<td class="no" ';
            echo ' onClick="acl_update(\'', $role , '\', \'',$task ,'\',\'delete\')';
            echo '">NO</td>', "\n";
            break;
    }
    ?>
    <?php } ?>
        <td class="yes" style="width: 2em" <?php
            echo ' onClick="acl_update(\'*\', \'',$task ,'\',\'yes\')"' ?>
            >Y</td>
        <td class="no"  style="width: 2em" <?php
            echo ' onClick="acl_update(\'*\', \'',$task ,'\',\'no\')"' ?>>N</td>
        <td class="null" style="width: 2em"  <?php
            echo ' onClick="acl_update(\'*\', \'',$task ,'\',\'delete\')"' ?>>?</td>
    </tr>
    <?php } ?>
    <tr><th>&nbsp;</th>
    <?php foreach($this->roles as $role) if (array_key_exists($role, $this->grants)){ ?>
       <?php
               echo '<td class="yes" ';
            echo ' onClick="acl_update(\'', $role , '\', \'','*' ,'\',\'yes\')';
            echo '">Yes</td>', "\n";

       ?>
        <?php } ?>
    </tr>

    <tr><th>&nbsp;</th>
    <?php foreach($this->roles as $role) if (array_key_exists($role, $this->grants)){ ?>
       <?php
               echo '<td class="no" ';
            echo ' onClick="acl_update(\'', $role , '\', \'','*' ,'\',\'no\')';
            echo '">No</td>', "\n";

       ?>
        <?php } ?>
    </tr>

    <tr><th>&nbsp;</th>
    <?php foreach($this->roles as $role) if (array_key_exists($role, $this->grants)){ ?>
       <?php
               echo '<td class="null" ';
            echo ' onClick="acl_update(\'', $role , '\', \'','*' ,'\',\'delete\')';
            echo '">???</td>', "\n";

       ?>
        <?php } ?>
    </tr>

</table>
<?php if (!$this->ticket) { ?>
</div>

<hr />

<?php echo $this->partial('forms/add_role.phtml') ?>

<?php echo $this->partial('forms/add_grant.phtml') ?>
<?php } ?>