<?php if (!$this->ticket) { ?>
<div id="acl_table">
<?php } ?>
<?php echo $this->partial('partials/acl_table.phtml', array('roles' => $this->roles,
    'tasks' => $this->tasks, 'grants' => $this->grants )) ?>
    <p>Note - these are site wide grants -
        groups and events have their own local &quot;grant space&quot;.
<?php if (!$this->ticket) { ?>
</div>

<hr />

<?php echo $this->partial('forms/add_role.phtml') ?>

<?php echo $this->partial('forms/add_grant.phtml') ?>
<?php } ?>