<h1>Groups</h1>

<div id="tabs">
    <ul>
        <li><a href="<?php echo $this->baseURL('/group/list/ticket/1') ?>">All Groups</a></li>
        <li><a href="<?php echo $this->baseURL('/group/my/ticket/1') ?>">My Groups</a></li>
        <li><a href="<?php echo $this->baseURL('/group/local/ticket/1') ?>">Local Groups</a></li>
        <li><a href="<?php echo $this->baseURL('/group/add/ticket/1') ?>">Add Group</a></li>
    </ul>
</div>

<script language="javascript">
    $(function() {
        $( "#tabs" ).tabs();
    });

</script>