<?php if (!$this->ticket) { ?>
    <h1>Group Settings</h1>
<?php } ?>
<div class="demo">

    <div id="accordion" style="height: 60em">
        <h3><a href="#">Questions for New Members</a></h3>

        <div id="questions">

        </div>
        <h3><a href="#">Member Permissions</a></h3>
        <div id="permissions"></div>
        <h3><a href="#">Exposure</a></h3>
        <div></div>
        <h3><a href="#">Section 4</a></h3>
        <div>
            <p>
		Cras dictum. Pellentesque habitant morbi tristique senectus et netus
		et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
		faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
		mauris vel est.
            </p>
            <p>
		Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
		Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
		inceptos himenaeos.
            </p>
        </div>
    </div>

</div>

<script>
    var accordian_urls = ['',
        '<?php echo $this->baseURL('/group/acl/id/' . $this->group->id . '/ticket/1') ?>',
        '<?php echo $this->baseURL('/group/exposure/id/' . $this->group->id . '/ticket/1') ?>',
    ]
    $(function() {
        $( "#accordion" ).accordion({
            autoHeight: false,
            height: '60em',
            changestart: function(event, ui){
                if (ui.newContent.is(':empty')){
                    var i = (ui.newContent.index() - 1) /2;
                    var url = accordian_urls[i];
                 //   alert('loading ' + i + ': ' + url);
                    
                     ui.newContent.load(url);
                }
            }

        });
    });

    $('#questions').load('<?php echo $this->baseUrl("/group/addquestions/id/{$this->group->id }/ticket/1") ?>');
</script>