<?php
if (empty($this->ticket)) { ?>
    <h1>Group&quot;<?php
    echo $this->group->name; ?>&quot;</h1>

    <div id="tabs">
        <ul>
            <li><a href="<?php echo $this->baseURL('/group/show/id/' . $this->group->id . '/ticket/1') ?>">Home</a></li>
            <li><a href="<?php echo $this->baseURL('/event/list/group_id/' . $this->group->id . '/ticket/1') ?>">Events</a></li>
            <li><a href="<?php echo $this->baseURL('/event/add/group_id/' . $this->group->id . '/ticket/1') ?>">Add Event</a></li>
            <li><a href="<?php echo $this->baseURL('/group/members/id/' . $this->group->id . '/ticket/1') ?>">Members</a></li>
            <li><a href="<?php echo $this->baseURL('/group/settings/id/' . $this->group->id . '/ticket/1') ?>">Settings</a></li>
        </ul>
    </div>

<?php
    if ($this->member_group){ ?>
<p>You are a member of this group</p>
<?php
} else { ?>
<div id="inner">
    <?php if ($this->user) { ?>
<p><a href="<?php echo $this->baseUrl('/group/join/id/' . $this->group->id) ?>"
      class="button submit">Join this group!</a></p>
<?php } else { ?>

<p><a href="<?php echo $this->baseUrl('/member/') ?>"
      class="button submit">Sign Up/Log In</a> if you want to join this group</p>
<?php } ?>
<?php } ?>
</div>
      
    <script language="javascript">
        $(function() {
            $( "#tabs" ).tabs();
        });
        
        
    function acl_update(role, task, can){
        $.post( '<?php echo $this->baseUrl('/group/grant') ?>',
        {acl: {role: role, task: task, can: can,
                scope: 'group',
                scope_id: '<?php echo (int) $this->group->id ?>'}, ticket: 1},
        function(table){$('#permissions').html(table)} )
    }
    </script>
<?php
} else {
?>
<?php
    echo $this->partial('tickets/group.phtml', array('group' => $this->group));
}