<?php
if (empty($this->ticket)) {
    echo '<h1>Group&quot;', $this->group->name, '&quot;</h1>';
?>
    

    <div id="tabs">
        <ul>
            <li><a href="<?php echo $this->baseURL('/group/show/id/' . $this->group->id . '/ticket/1') ?>">Home</a></li>
            <li><a href="<?php echo $this->baseURL('/event/list/group_id/' . $this->group->id . '/ticket/1') ?>">Events</a></li>
            <li><a href="<?php echo $this->baseURL('/event/add/group_id/' . $this->group->id . '/ticket/1') ?>">Add Event</a></li>
            <li><a href="<?php echo $this->baseURL('/group/members/id/' . $this->group->id . '/ticket/1') ?>">Members</a></li>
        </ul>
    </div>

<?php
    if ($this->member_group){ ?>
<p>You are a member of this group</p>
<?php
} else { ?>
<div id="inner">
<p><a href="<?php echo $this->baseUrl('/group/join/id/' . $this->group->id) ?>"
      class="button submit">Join this group!</a></p>
</div>
<?php } ?>
      
    <script language="javascript">
        $(function() {
            $( "#tabs" ).tabs();
        });
    </script>
<?php
} else {
?>
<?php
    echo $this->partial('tickets/group.phtml', array('group' => $this->group));
}